apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.eien.freevision.sk
  labels:
    owner: eien.freevision.sk
spec:
  group: eien.freevision.sk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
  scope: Cluster
  names:
    plural: apps
    singular: app
    kind: App
    shortNames:
      - app
