apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.eien.freevision.sk
  labels:
    owner: eien.freevision.sk
spec:
  group: eien.freevision.sk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                domain:
                  type: string
      additionalPrinterColumns:
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Domain
          type: string
          jsonPath: .spec.domain
  scope: Namespaced
  names:
    plural: domains
    singular: domain
    kind: Domain
    shortNames:
      - dom
