apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: processes.eien.freevision.sk
  labels:
    owner: eien.freevision.sk
spec:
  group: eien.freevision.sk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                image:
                  type: string
                config:
                  type: string
                secret:
                  type: string
                command:
                  type: array
                  items:
                    type: string
                replicas:
                  type: integer
                ports:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
      additionalPrinterColumns:
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Command
          type: string
          jsonPath: .spec.command
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Ports
          type: string
          jsonPath: .spec.ports[*]
  scope: Namespaced
  names:
    plural: processes
    singular: process
    kind: Process
    shortNames:
      - proc
