apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: routes.eien.freevision.sk
  labels:
    owner: eien.freevision.sk
spec:
  group: eien.freevision.sk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                domains:
                  type: array
                  items:
                    type: string
                path:
                  type: string
                process:
                  type: string
                port:
                  type: string
      additionalPrinterColumns:
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Domains
          type: string
          jsonPath: .spec.domains[*]
        - name: Path
          type: string
          jsonPath: .spec.path
        - name: Process
          type: string
          jsonPath: .spec.process
        - name: Port
          type: string
          jsonPath: .spec.port
  scope: Namespaced
  names:
    plural: routes
    singular: route
    kind: Route