name: Test

on: [push]

jobs:
#  ruby-specs:
#    runs-on: ubuntu-latest
#
#    name: "Specs - Ruby ${{ matrix.ruby }}"
#    strategy:
#      fail-fast: false
#      matrix:
#        ruby:
#          - '3.1.2'
#          - '3.0.3'
#          - '3.0.2'
#          - '3.0.1'
#          - '3.0'
#          - '2.7'
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Ruby ${{ matrix.ruby }}
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: ${{ matrix.ruby }}
#          bundler-cache: true
#
#      - name: Run specs
#        run: |
#          bin/rspec

  build-and-publish-rubygem:
#    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
#    needs:
#      - ruby-specs
    name: Build and Publish Rubygem
    permissions:
      contents: read
      packages: write

    env:
      RUBY_VERSION: 3.1.2

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Ruby ${{env.RUBY_VERSION}}"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{env.RUBY_VERSION}}"

      - name: Publish to Github Package repository
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
