name: Release

on:
  release:
    types: [published]
  create:
    tags:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish Rubygem
    permissions:
      contents: read
      packages: write

    env:
      RUBY_VERSION: 3.1.2

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Ruby ${{env.RUBY_VERSION}}"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{env.RUBY_VERSION}}"

      - name: "Set new rubygem version"
        run: |
          sed -i 's/VERSION.*/VERSION = "${{ github.event.create.ref }}"/' lib/eien/version.rb
          git add lib/eien/version.rb
          git diff --cached

#      - name: Publish to RubyGems
#        run: |
#          mkdir -p $HOME/.gem
#          touch $HOME/.gem/credentials
#          chmod 0600 $HOME/.gem/credentials
#          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#          gem build *.gemspec
#          gem push *.gem
#        env:
#          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
