name: Rubygem

#on:
#  push:
#    tags:
#      - *
on: [push]

env:
  RUBY_VERSION: 3.1.2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build + Publish
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Ruby ${{RUBY_VERSION}}"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{RUBY_VERSION}}"

      - name: Publish to Github Package repository
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          # gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          # gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"